Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["sharedfolder", "add", :id, "--name", "packer-mikrotik",
      "--hostpath", File.expand_path("../..", File.dirname(__FILE__))]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ruby_development_provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.become = false
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end
