Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["sharedfolder", "add", :id, "--name", "packer-mikrotik",
      "--hostpath", File.expand_path("../..", File.dirname(__FILE__))]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provider "libvirt" do |lv, override|
    override.vm.box = "generic/ubuntu2204" # 1804 does not have virtiofs support.
    lv.qemu_use_session = false # required for virtiofs.
    lv.memory = 2 * 1024
    lv.cpus = 2
    lv.memorybacking :source, :type => 'memfd'  # required for virtiofs.
    lv.memorybacking :access, :mode => 'shared' # required for virtiofs.
    override.vm.synced_folder File.expand_path("../..", File.dirname(__FILE__)), "/mnt/packer-mikrotik", type: "virtiofs"
    override.vm.synced_folder ".", "/vagrant", type: "virtiofs"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ruby_development_provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.become = false
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end
